# Numpy (Numerical Python) Library

In [1]:
a=5
b=6
print(a+b)

11


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import numpy as np

In [22]:
a=np.arange(15)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [24]:
type(a)

numpy.ndarray

In [27]:
b=a.reshape(3,5)


b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
b.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
np.transpose(b)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [36]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
b=np.arange(8).reshape(2,4)

In [44]:
b=np.arange(8)
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
b.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
c=b.reshape(2,2,2)

In [47]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
c=np.arange(9).reshape(3,3)

In [49]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
b=np.array([4,5,6])

b

array([4, 5, 6])

In [57]:
np.add(c,b)

array([[ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14]])

In [58]:
np.subtract(c,b)

array([[-4, -4, -4],
       [-1, -1, -1],
       [ 2,  2,  2]])

In [59]:
np.multiply(c,b)

array([[ 0,  5, 12],
       [12, 20, 30],
       [24, 35, 48]])

In [60]:
np.divide(c,b)

array([[0.        , 0.2       , 0.33333333],
       [0.75      , 0.8       , 0.83333333],
       [1.5       , 1.4       , 1.33333333]])

In [61]:
np.divide(b,c)

C:\Users\Minhazul Alam\AppData\Local\Temp\ipykernel_16160\52826608.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(b,c)


array([[       inf, 5.        , 3.        ],
       [1.33333333, 1.25      , 1.2       ],
       [0.66666667, 0.71428571, 0.75      ]])

In [62]:
np.divide(c,b)

array([[0.        , 0.2       , 0.33333333],
       [0.75      , 0.8       , 0.83333333],
       [1.5       , 1.4       , 1.33333333]])

In [63]:
y=np.arange(17)

In [64]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [65]:
y[:6]

array([0, 1, 2, 3, 4, 5])

In [68]:
y[6:10]

array([6, 7, 8, 9])

In [69]:
slice(0,17,3)

slice(0, 17, 3)

In [74]:
z=slice(3,16,3)

In [75]:
y[z]

array([ 3,  6,  9, 12, 15])

# Print Numpy

In [76]:
for i in np.nditer(y):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


# Numpy Split

In [77]:
a=np.arange(9)

In [78]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [85]:
np.split(a,[3,5,7])

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]